"""What the page must never say.

Most of these are not "does it render" — they are assertions about claims. A status page's failure
mode is not a crash, it is confidently telling a stranger something untrue: that a day nobody
measured was an outage, that everything is fine according to data from yesterday, or that a
component exists which nothing is watching.
"""

from __future__ import annotations

import datetime as dt
import json

import pytest

from bakobo_status import site
from bakobo_status.incidents import Store
from bakobo_status.snapshot import Now, Snapshot

TODAY = dt.date(2026, 9, 5)
BUILT = dt.datetime(2026, 9, 5, 22, 30, tzinfo=dt.timezone.utc)
COMPONENTS = {
    "witness-de": {"display": "DE witness — de.wit.bakobo.com", "kind": "witness"},
    "bakobo-com": {"display": "bakobo.com", "kind": "web"},
}


def day(uptime=1.0, reachability=1.0, intervals=96, executions=288, failures=0):
    return {
        "uptime": uptime, "reachability": reachability, "intervals": intervals,
        "executions": executions, "failures": failures,
    }


@pytest.fixture()
def estate(tmp_path):
    (tmp_path / "history").mkdir()
    (tmp_path / "incidents").mkdir()
    (tmp_path / "history" / "witness-de.json").write_text(json.dumps({
        "component": "witness-de",
        "days": {"2026-09-05": day(), "2026-09-04": day(uptime=0.5, failures=144)},
    }))
    return tmp_path


# --- the claims ---------------------------------------------------------------------------------

def test_a_day_with_no_record_is_not_an_outage():
    """The pixel version of the bug the backfill shipped. A gap must not be coloured as down."""
    assert site.day_state(None) == "no-data"
    assert site.day_state(day(uptime=0.0, intervals=0, executions=0)) == "no-data"
    assert site.day_state(day(uptime=0.0, intervals=96)) == "down"


@pytest.mark.parametrize(
    ("uptime", "expected"),
    [(1.0, "operational"), (0.999, "operational"), (0.99, "degraded"), (0.5, "down")],
)
def test_bar_states_match_the_stored_thresholds(uptime, expected):
    assert site.day_state(day(uptime=uptime)) == expected


def test_the_window_keeps_gaps_as_gaps():
    """A strip that closed up its gaps would compress a week of missing data into nothing and
    read as continuous coverage."""
    rows = site.window({"2026-09-05": day()}, TODAY, span=5)
    assert len(rows) == 5
    assert [d.isoformat() for d, _ in rows][0] == "2026-09-01"
    assert rows[-1][0] == TODAY
    assert [r for _, r in rows].count(None) == 4


def snap(current=1, minutes_ago=5, intervals=90, up=90):
    return Snapshot(
        current=current,
        as_of=(BUILT - dt.timedelta(minutes=minutes_ago)).isoformat(),
        intervals=intervals,
        up=up,
    )


def test_the_banner_no_longer_infers_green_from_silence():
    """It used to say "All systems operational" whenever no incident file existed. Nothing alerts
    and incidents are declared by hand, so that was a green light generated by the absence of
    information -- an outage at 3am produced exactly the same silence as a healthy night."""
    state, headline, evidence = site.banner([], {}, BUILT, 2)
    assert state == "no-data"
    assert headline == "Current status unknown"
    assert "not a report of an outage" in evidence


def test_the_banner_says_operational_only_with_a_live_measurement_behind_it():
    state, headline, evidence = site.banner([], {"a": snap(), "b": snap()}, BUILT, 2)
    assert (state, headline) == ("operational", "All systems operational")
    assert "All 2 probed and responding as of 22:25 UTC." == evidence


def test_the_banner_reports_an_outage_nobody_has_declared():
    """The point of the whole exercise. A witness that stopped answering at 3am now reaches the
    banner on the strength of the probes, without waiting for a human to notice and type."""
    state, headline, evidence = site.banner([], {"a": snap(), "witness-de": snap(current=0)}, BUILT, 2)
    assert (state, headline) == ("down", "1 of 2 not responding")
    assert evidence.startswith("witness-de, as of")


def test_a_stale_snapshot_is_not_evidence_of_anything():
    """Grey, not red: an Actions outage or an expired token has nothing to do with whether the
    estate is up, so a stopped harvest must not be published as an outage."""
    state, headline, evidence = site.banner([], {"a": snap(minutes_ago=90)}, BUILT, 1)
    assert (state, headline) == ("no-data", "Current status unknown")
    assert "Nothing measured since 21:00 UTC." in evidence


def test_a_partially_measured_estate_does_not_claim_to_be_whole():
    state, headline, _ = site.banner([], {"a": snap()}, BUILT, 3)
    assert (state, headline) == ("operational", "1 of 3 responding")


def test_an_open_incident_outranks_the_measurement(estate):
    """A person's statement carries a cause and a remedy; a probe result carries neither. So an
    open incident wins even when every probe is green -- which is the case during a partial
    degradation the checks cannot see."""
    store = Store(estate / "incidents")
    store.open(title="Slow", severity="minor", components=["witness-de"], message="m",
               known_components=["witness-de"], now=BUILT)
    state, headline, _ = site.banner(store.all(), {"a": snap()}, BUILT, 1)
    assert (state, headline) == ("degraded", "1 open incident")


def test_the_banner_takes_the_worst_open_severity(estate):
    store = Store(estate / "incidents")
    store.open(title="Slow", severity="minor", components=["witness-de"], message="m",
               known_components=["witness-de"], now=dt.datetime(2026, 9, 5, 1,
                                                                tzinfo=dt.timezone.utc))
    store.open(title="Gone", severity="critical", components=["witness-de"], message="m",
               known_components=["witness-de"], now=dt.datetime(2026, 9, 5, 2,
                                                                tzinfo=dt.timezone.utc))
    state, headline, _ = site.banner(store.all(), {}, BUILT, 1)
    assert state == "down"
    assert headline == "2 open incidents"


# --- rendering ----------------------------------------------------------------------------------

def test_the_page_is_self_contained(estate):
    """It is read when other things are broken, so every external request is a way for it to be
    broken too."""
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "<script" not in page
    assert "<link" not in page          # no stylesheet, no font, no preconnect
    assert "src=" not in page           # no image, no iframe, no embed
    assert "@import" not in page
    assert "http://" not in page

    # The only external URL is the security.txt link, and it is a navigation the reader chooses
    # rather than a resource the page fetches. Nothing has to resolve for the page to render.
    assert page.count("https://") == 1
    assert "https://bakobo.com/.well-known/security.txt" in page


def test_every_component_appears_with_a_text_state(estate):
    """Colour never carries meaning alone -- the house standard's mitigation for the amber step,
    which is below 3:1 on any light surface and cannot be re-stepped."""
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    for meta in COMPONENTS.values():
        assert meta["display"] in page
    assert "Operational" in page
    assert "No data" in page


def test_a_component_with_no_history_still_renders(estate):
    """bakobo-com has no history file here. A missing file must not omit the component, or the
    page would silently stop mentioning something it is supposed to be watching."""
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "bakobo.com" in page
    assert "not yet measured" in page


def test_the_page_says_it_is_a_snapshot(estate):
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "snapshot, not a live view" in page
    assert "2026-09-05 22:30 UTC" in page


def test_the_security_address_is_advertised(estate):
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "mailto:security@bakobo.com" in page
    assert "/.well-known/security.txt" in page


def test_incident_text_is_escaped(estate):
    """Incident prose is written by a human under time pressure and is published verbatim."""
    store = Store(estate / "incidents")
    store.open(title="<script>alert(1)</script>", severity="major", components=["witness-de"],
               message="a & b <b>bold</b>", known_components=["witness-de"], now=BUILT)
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "<script>alert(1)</script>" not in page
    assert "&lt;script&gt;" in page
    assert "a &amp; b" in page


def test_resolved_incidents_appear_under_recent_not_current(estate):
    store = Store(estate / "incidents")
    inc = store.open(title="Gone", severity="major", components=["witness-de"], message="m",
                     known_components=["witness-de"], now=BUILT)
    store.append(inc.id, state="resolved", message="Fixed.",
                 now=BUILT + dt.timedelta(hours=1))
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "No open incidents." in page
    assert "Current status unknown" in page  # no snapshot in this fixture
    assert "Fixed." in page


def test_the_numbers_table_is_present_for_a_measured_component(estate):
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "<table>" in page
    assert "Reachability" in page
    assert "100.00%" in page


def test_a_tooltip_explains_an_empty_day_rather_than_leaving_it_bare(estate):
    """A grey bar with no explanation is read as an outage by anyone not told otherwise."""
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "No data — nothing was being measured on this day." in page


def test_history_for_an_absent_file_is_empty(tmp_path):
    assert site.load_history(tmp_path, "nope") == {}


# --- today, the cell a reader actually came for --------------------------------------------------

def written_now(tmp, **kw):
    path = tmp / "now.json"
    Now(path).write(BUILT, {"witness-de": snap(**kw), "bakobo-com": snap()})
    return path


def test_today_is_green_while_nothing_has_failed(estate):
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT,
                       now_path=written_now(estate))
    assert "All systems operational" in page
    assert "up right now, as of 22:25 UTC" in page
    assert "Projects to 100.00% if it stays this way" in page


def test_today_goes_red_while_an_outage_is_happening(estate):
    """The whole point. One failed interval with the outage still active projects the rest of the
    day as down, and the cell says so within fifteen minutes rather than within seventy-five."""
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT,
                       now_path=written_now(estate, current=0, intervals=48, up=47))
    assert "DOWN right now" in page
    assert "1 of 2 not responding" in page
    assert site.STATE_COLOURS["down"] in page


def test_a_stopped_harvest_leaves_today_grey_and_says_why(estate):
    """Grey rather than red, and never silently grey: an unexplained grey cell is read as an
    outage by anyone who has not been told otherwise."""
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT,
                       now_path=written_now(estate, minutes_ago=200))
    assert "Measurement stopped at 19:10 UTC" in page
    assert "it is the monitoring that went quiet" in page


def test_today_is_marked_as_still_in_progress(estate):
    """A cell identical to its ninety neighbours would claim today is finished and scored."""
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT,
                       now_path=written_now(estate))
    assert page.count('class="day today"') == len(COMPONENTS)
    assert "— today</strong>" in page


def test_a_component_with_no_reading_is_absent_rather_than_down(estate):
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT)
    assert "No harvest has run against this component yet" in page
    assert "Current status unknown" in page


def test_a_snapshot_naming_a_retired_component_cannot_reach_the_banner(estate):
    """A row nobody can see must not be able to put "1 of 2 not responding" above the fold."""
    path = estate / "now.json"
    Now(path).write(BUILT, {"witness-de": snap(), "bakobo-com": snap(),
                            "gone-last-week": snap(current=0)})
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT, now_path=path)
    assert "All systems operational" in page
    assert "gone-last-week" not in page


def test_the_page_still_reaches_no_network_with_a_snapshot(estate):
    page = site.render(COMPONENTS, estate / "history", estate / "incidents", BUILT,
                       now_path=written_now(estate))
    assert "<script" not in page
    assert page.count("https://") == 1
